MODEL:
  TYPE: AutoFormerSub
  NUM_CLASSES: 100
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: 192
  DEPTH: 13
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
AUTOFORMER_SEARCH_SPACE:
  HIDDEN_DIM: [192, 216, 240]
  MLP_RATIO: [3.5, 4.0]
  DEPTH: [12, 13, 14]
  NUM_HEADS: [3, 4]
AUTOFORMER_SUBNET:
  HIDDEN_DIM: 240
  MLP_RATIO: [4.0, 3.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.5, 4.0, 4.0, 4.0, 3.5]
  DEPTH: 13
  NUM_HEADS: [3, 3, 3, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3]
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
DISTILLATION: 
  ENABLE_INTER: True
  INTER_TRANSFORM: linear
  INTER_TEACHER_INDEX: [0, 1, 2]
  INTER_STUDENT_INDEX: [0, 6, 11]
  INTER_WEIGHT: 2.5
  TEACHER_MODEL: ResNet
  TEACHER_WEIGHTS: work_dirs/r-56_c100/model.pyth
  TEACHER_IMG_SIZE: 32
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
