MODEL:
  TYPE: PiT
  NUM_CLASSES: 102
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: [64, 128, 256]
  DEPTH: [2, 6, 4]
  NUM_HEADS: [2, 4, 8]
  MLP_RATIO: 4
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
PIT_SEARCH_SPACE:
  BASE_DIM: [16, 24, 32, 40]
  MLP_RATIO: [2, 4, 6, 8]
  DEPTH: [[1, 2, 3], [4, 6, 8], [2, 4, 6]]
  NUM_HEADS: [[2, 4, 8], [2, 4, 8], [2, 4, 8]]
PIT_SUBNET:
  BASE_DIM: 24
  MLP_RATIO: 6
  DEPTH: [1, 8, 4]
  NUM_HEADS: [2, 4, 8]
PIT:
  STRIDE: 8
CNN:
  DEPTH: 56
RESNET:
  TRANS_FUN: basic_transform
DISTILLATION:
  ENABLE_INTER: True
  INTER_TRANSFORM: linear
  INTER_TEACHER_INDEX: [0, 1, 2]
  INTER_STUDENT_INDEX: [0, 6, 11]
  INTER_WEIGHT: 2.5
  TEACHER_MODEL: ResNet
  TEACHER_WEIGHTS: work_dirs/r-56_flower/model.pyth
  TEACHER_IMG_SIZE: 32
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: flowers
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: flowers
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False

