CNN:
  DEPTH: 56
CUDNN:
  BENCHMARK: false
DATA_LOADER:
  NUM_WORKERS: 4
DISTILLATION:
  ENABLE_INTER: true
  INTER_STUDENT_INDEX:
  - 0
  - 6
  - 11
  INTER_TEACHER_INDEX:
  - 0
  - 1
  - 2
  INTER_TRANSFORM: linear
  INTER_WEIGHT: 2.5
  TEACHER_IMG_SIZE: 32
  TEACHER_MODEL: ResNet
  TEACHER_WEIGHTS: work_dirs/r-56_flower/model.pyth
MODEL:
  NUM_CLASSES: 102
  TYPE: PiT
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.0005
  LR_POLICY: cos
  MAX_EPOCH: 300
  MIN_LR: 5.0e-06
  OPTIMIZER: adamw
  WARMUP_EPOCHS: 20
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.05
PIT:
  STRIDE: 8
PIT_SEARCH_SPACE:
  BASE_DIM:
  - 16
  - 24
  - 32
  - 40
  DEPTH:
  - - 1
    - 2
    - 3
  - - 4
    - 6
    - 8
  - - 2
    - 4
    - 6
  MLP_RATIO:
  - 2
  - 4
  - 6
  - 8
  NUM_HEADS:
  - - 2
    - 4
    - 8
  - - 2
    - 4
    - 8
  - - 2
    - 4
    - 8
PIT_SUBNET:
  BASE_DIM: 40
  DEPTH:
  - 3
  - 6
  - 4
  MLP_RATIO: 8
  NUM_HEADS:
  - 4
  - 4
  - 8
PROXY_DATASET: flowers
RESNET:
  TRANS_FUN: basic_transform
TEST:
  BATCH_SIZE: 200
  DATASET: flowers
  SPLIT: test
TRAIN:
  BATCH_SIZE: 128
  DATASET: flowers
  SPLIT: train
TRANSFORMER:
  ATTENTION_DROP_RATE: 0.0
  DEPTH:
  - 2
  - 6
  - 4
  DROP_PATH_RATE: 0.1
  DROP_RATE: 0.0
  HIDDEN_DIM:
  - 64
  - 128
  - 256
  MLP_RATIO: 4
  NUM_HEADS:
  - 2
  - 4
  - 8
  PATCH_SIZE: 16
