MODEL:
  TYPE: DeiT
  NUM_CLASSES: 1000
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: 192
  DEPTH: 12
  NUM_HEADS: 3
  MLP_RATIO: 4
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 1024
  MIXED_PRECISION: True
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 1024
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 16
CUDNN:
  BENCHMARK: True
