MODEL:
  TYPE: AutoFormerSub
  NUM_CLASSES: 4
TRANSFORMER:
  PATCH_SIZE: 16
  HIDDEN_DIM: 192
  DEPTH: 13
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  ATTENTION_DROP_RATE: 0.0
AUTOFORMER_SEARCH_SPACE:
  HIDDEN_DIM: [192, 216, 240]
  MLP_RATIO: [3.5, 4.0]
  DEPTH: [12, 13, 14]
  NUM_HEADS: [3, 4]
AUTOFORMER_SUBNET:
  HIDDEN_DIM: 192
  MLP_RATIO: [3.5, 3.5, 3.0, 3.5, 3.0, 3.0, 4.0, 4.0, 3.5, 4.0, 3.5, 4.0, 3.5]
  DEPTH: 13
  NUM_HEADS: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3]
OPTIM:
  OPTIMIZER: adamw
  BASE_LR: 5.0e-4
  MIN_LR: 5.0e-6
  LR_POLICY: cos
  MAX_EPOCH: 300
  WEIGHT_DECAY: 0.05
  WARMUP_FACTOR: 0.001
  WARMUP_EPOCHS: 20
TRAIN:
  DATASET: chaoyang
  SPLIT: train
  BATCH_SIZE: 128
TEST:
  DATASET: chaoyang
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
